database:
  db: neuvix

# 目前neuvix业务表没有主从联系，没有外键
table-configs:
  change_ship_archives_basic_info: # 写主表，没主表则随机
    tables: ["change_ship_archives_basic_info"]  # 所有表放在一个列表里
    foreign_keys:
    
  change_driver_basic_info:
    tables: ["change_driver_basic_info"]
    foreign_keys:
  
  change_route_basic_info:
    tables: ["change_route_basic_info"]
    foreign_keys:
    
  change_shipping_basic_work_data:
    tables: ["change_shipping_basic_work_data"]
    foreign_keys:

  # store-computer:
  #   ## 表，主表第一个，必须，从表，建议按你想要的顺序依次列出
  #   tables: ["store","store_computer"]
  #   ## 各表的主键
  #   primary_keys:
  #     "store": "entity_id"
  #     "store_computer": "entity_id"
  #   ## 表之间的主外键关系
  #   foreign_keys:
  #     "store_computer_fk": [{"store":"entity_id"},{"store_computer":"store_id"}]